language: go
services:
- docker
go:
- '1.13'
env:
  global:
  - REPO=xtradio/api
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: nvKiIsCqKM+xZqMS75NjDit5zasgMbi5vSEs5A0zHWjWeGXVn4cmF5g15+NfUxM69dOEy9NFyXTHzjESwCX1S4BnupelOGO5Bo+Q/UPYcqQqKPph0ZoSYJuH3xuk2jrKGVKTq5bGT7dQjXxhxUb13SRiXPav1H897Yykmrd64mEAbPkce8fZlcXSAzOg/KgcFetiLztzeMeUUi4hS3jK7gntdrfZIbxcqwx9qxKEFprsP2Q69tQOCS7plch8EJCptOLFFvWytZ0yjHuQ0PYTXWEjBf+uu0MXrPtI8Mp/XNGM4uTnMQrtz6EGZ2NooeN0+Zkf9ZyrvY1HL+qPNj9TjYjLSsmzhenY60AAJ3u9KChybtwQ/6dN754V3qNQqhtGCl8zoGfKRbaiycYedCCuk1TpIhe2dIU2Zi8D0SYKYvnFHDkUd9ABZFN8vTTgpLlV5l4rl5Op2F3grF0RjplyJUGF3tYqqORj77VhU7Dlzs6pt+cpQRSjuwcKGtrifhNh2t7aZ5T3nkihkBLQ8k6QRQtG1jIkj9LkCB3jM5+MOWSHS2/btq4S/fjRDowMLQxJ7VdLziwXRsE59Q8chnainVuIb6Jjhfmm25JxVcjpJ7JfeWpB29BPWm44KNHOwDZVBKg2Z3TpoeS32n+GR/yLavJlOcwCXkLadPIWwjsrQ8s=
  - secure: WIC6B2Tfy0f8cDFKTrMXaMdNpZd39HdTxAeUX7UeyVmb+SOWlEMRZ2sqqnkS7f/7b47furc0s8/DAlIFyFMRiXn2Gk4RO3P2Imm7sPD//77ftXX9HtpD8d6k7DBEF9lJl4vPRMvkNyMqDT75o4WegRCB69ayshQWqQ7e76FJjy4M3eAlY/ZriS3s0v8zHEEMmBai+qWrTRG8UfUUaY4hXvs0xwNNdnNllZYdIHZemxpe1JCKSDxyD/dtrMDFrTjhqHOdhXUr8n4Ur/Bb+mjSlSKgzZFeqQOcRkeWk3AxY4S8/dhUTDcRMniJgQjr1VT0kHjwTc/5iQdO9yu0Wfk1XQPPQs+oymDP9sD4xoZsJu++3GtUWkCZcsMKNaQ3W0CDYgWhahQzhdOs+ZCib+Eo+JSTCDCSCuHgGh1TmATDGUA4i2wJEZ14vxrjyHMR2iSENBpdWzWOh9H8OTsfUiRbcWJ0EqvGNCDkTyRJmJJ46/eLP0qMhJYAzV79UCoVrcs/qShNhAQ8QcH+J8z1kAaMYY9cTV1ZiSHqamgSTVnogCjn2353OBxq4xnb/oZftVXRREDlQNxowMHXly6xFeeCSPG7/HYSySwzTjxjGgeKxG+TZqMBcn2ex6wD8mNLzZmLF5jci6qCk51kVsG9jUc1C6MIkFYqhRKEm2WrXAYUPFc=
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: QGX/KihrhG2fi1PkvXimOjhXbUVF1PNCzqPqz/zTfbOga6O08G8MkW72VBWHkqhI7uWteJB3Pj0nMNGH9+/5pHBSlzwohz6zbetHypt0S7UFjH4Yc8aXQXAWO5Z7NKTCDaIW3E+uPuigODy84xOf21dzl08xNOOWx2xMHA53iXOG4ceX3faAM6kQCTCIPrxqFRiXKwn1HDWa7BjYGdYgQZzI6/6TWBsc0K+phvqVRQ0zGDQh84e0oOLhNxNUMvt6q0CCiLOQC6mTMEPmpESRkcBgNj/s9wEcKHnfTRcoLne6UFdoHCOOTbUSavZnTo2AkIvpbK6uwTZHz/J7A0EEkTNbwQgBgFpYcG4vRX5MWmHXnusIHh5GkNLzTmR9Xsdv24xsuA0D8XFXGDYvuqobVkbd4PivuCAqvn5ynHzqQWepr4sx6Atx+q2aArm1g0Rrk01XoTlL3sW1SgP7vbdUnPe/PNgMMOA27yWjAbOByXGrteKTy5ZeFEoIvIhWhWO9d2Tho3pQbpwDfG/PlLXwWj3PdeEc5njDCAWI2xhzpI53JQe+cwslMzO0xPFrCZP9nfyf0yukHmyJ+hmkSh8nLuUtpxKFBq+NkTZTtGH9cfFg8TwoT2m6PVT55BEPsTLNeB7lTS0eNr4Sh7AX+IKYCDKa2+4OyaAKWy+lN2HzZ9E=
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push $REPO:$TAG
- docker push $REPO:$COMMIT
