name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      GO111MODULE: off
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get go dependencies
        run: go get

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Run unit tests
        run: go test -v -cover

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            xtradio/api:latest
            xtradio/api:${GITHUB_SHA::8}
